version: '3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '81:80'   
  
  backend1:
    build: 
      context: ./backend
      dockerfile: Dockerfile

  backend2:
    build: 
      context: ./backend
      dockerfile: Dockerfile

  backend3:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      
  backend4:
    build: 
      context: ./backend
      dockerfile: Dockerfile